## Sample Component kind (Namespaced)
apiVersion: openchoreo.dev/v1alpha1
kind: Component
metadata:
  name: reading-list-node-service
  namespace: default-org
  annotations:
    openchoreo.dev/display-name: Reading List Node.js Component
    openchoreo.dev/description: A simple REST API service for managing a reading list, built with Node.js.
  labels:
    openchoreo.dev/organization: default-org
    openchoreo.dev/project: default-project
    openchoreo.dev/name: reading-list-node-service
spec:
  type: Service
  source:
    gitRepository:
      url: https://github.com/wso2/choreo-samples
      authentication:
        secretRef: choreo-bot-git-pat
---

## Sample DeploymentTrack kind (Namespaced)
apiVersion: openchoreo.dev/v1alpha1
kind: DeploymentTrack
metadata:
  name: reading-list-node-service-main
  namespace: default-org
  annotations:
    openchoreo.dev/display-name: Main Deployment Track
    openchoreo.dev/description: Deployment track for the Reading List Node.js service.
  labels:
    openchoreo.dev/organization: default-org
    openchoreo.dev/project: default-project
    openchoreo.dev/component: reading-list-node-service
    openchoreo.dev/name: reading-list-node-service-main
spec:
  buildTemplateSpec:
    branch: main
    path: /reading-books-list-service-nodejs
    buildConfiguration:
      buildpack:
        name: Node.js
---

## Sample Build kind (Namespaced)
apiVersion: openchoreo.dev/v1alpha1
kind: Build
metadata:
  name: reading-list-node-service-build-01
  namespace: default-org
  annotations:
    openchoreo.dev/display-name: Default Build
    openchoreo.dev/description: Initial build configuration for the Reading List Node.js service.
  labels:
    openchoreo.dev/organization: default-org
    openchoreo.dev/project: default-project
    openchoreo.dev/component: reading-list-node-service
    openchoreo.dev/deployment-track: reading-list-node-service-main
    openchoreo.dev/name: reading-list-node-service-build-01
spec:
  branch: main
  path: /reading-books-list-service-nodejs
  buildConfiguration:
    buildpack:
      name: Node.js
      version: 18.x.x
---

#### Sample Deployment kind (Namespaced)
apiVersion: openchoreo.dev/v1alpha1
kind: Deployment
metadata:
  name: reading-list-node-service-development-deployment-01
  namespace: default-org
  annotations:
    openchoreo.dev/display-name: Reading List Node.js Service Deployment
    openchoreo.dev/description: Initial deployment configuration for the Reading List Node.js service.
  labels:
    openchoreo.dev/organization: default-org
    openchoreo.dev/project: default-project
    openchoreo.dev/environment: development
    openchoreo.dev/component: reading-list-node-service
    openchoreo.dev/deployment-track: reading-list-node-service-main
    openchoreo.dev/name: reading-list-node-service-development-deployment-01
spec:
  deploymentArtifactRef: reading-list-node-service-build-01
