name: Release Quick Start Dev Container Image

on:
  workflow_dispatch:
  # TODO: move this release also to the other release workflow, once a proper method is found for multi arch builds
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.5'

      - name: Build choreoctl
        run: make choreoctl-release

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Read version from file
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: install/quick-start/Dockerfile
          push: true
          tags: ghcr.io/openchoreo/quick-start:v${{ env.VERSION }}, ghcr.io/openchoreo/quick-start:latest
          platforms: linux/amd64,linux/arm64
          context: .
